author: "Kevin Reuning"
project:
  type: website

website:
  title: "Presentations"
  site-url: "https://kevinreuning.com/presentations/"
  google-analytics: "G-Q4HC79ZRBZ"
  sidebar: false
  navbar: false

format:
  html:
    theme: cosmo
    css: styles.css
  revealjs: 
    df-print: tibble
    execute:
        echo: true


