author: "Kevin Reuning"
project:
  type: website
  execute-dir: project

website:
  title: "Presentations"
  site-url: "https://kevinreuning.com/presentations/"
  google-analytics: "G-Q4HC79ZRBZ"
  sidebar: false
  navbar: false

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: analytics.html
  revealjs: 
    theme: [default, custom_pres.scss]
    include-in-header: analytics.html
    execute:
        echo: true

knitr:
  opts_chunk:
    dev: svg

