[build]
publish = "_site"
#command = "quarto render"


#[[plugins]]
#  package = "netlify-plugin-hugo-cache-resources"
  
# [[plugins]]
#   package = "netlify-plugin-checklinks"
#   [plugins.inputs]
#   skipPatterns = ["https://plausible.io/js/script.js"]


[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://kevinreuning.com/presentations"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"


	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]

# [[plugins]]
# package = "netlify-plugin-image-optim"